.TH MBLAZE-DRAFT 1 "2026-08-29" "mblaze-draft"
.SH NAME
mblaze-draft \- handle MailDir drafts using dmenu
.SH SYNOPSIS
.B mblaze-draft
.RB [ \-h ]
.I FILE
.SH DESCRIPTION
Open a dmenu with options to send, add an attachment, or edit a MailDir FILE. 
.SH OPTIONS
.TP
.B \-h
Display the help and exit.
.TP
.I FILE
The draft file to handle. Must be in the MailDir format.
.SH ENVIRONMENT VARIABLES
The following variables must be set. 
.IP \(bu 2
LOGGER: Set the logging program, if none is set redirect to STDOUT.
.IP \(bu 2
EDITOR: The editor to open to edit the draft.
